EventTicket_Text_TrainerIsland:
	.string "So… it's come to it at last…\p"
	.string "What? Oh, I was just mumbling…\p"
	.string "Anyway, show me your ticket.$"

EventTicket_Text_ShowTrainerTicket:
	.string "Oh, my! That's a ticket to Trainer\n"
	.string "Island! Wonderful!\p"
	.string "All Aboard!$"

EventTicket_Text_TrainerIslandSailBack:
	.string "Trainer Island too much for ye, lad?\p"
	.string "Had enough battling for today?\p"
	.string "Want to sail back to LILYCOVE?$"

EventTicket_Text_Stay:
	.string "No, problem! Stay as long as you like!$"

TrainerIsland_Entrance_Text_Sign:
	.string "Trainer Island: Where the heated battles\n"
	.string "lie.$"

TrainerIsland_Entrance_Text_Tip:
	.string "INFO\p"
	.string "Trainers on trainer island are not\n"
	.string "your everyday average trainer.\p"
	.string "They are much stronger and have\n"
	.string "a variety of powerful moves at\l"
	.string "their disposal.\p"
	.string "It is recommended to bring your\n"
	.string "A-Game teams with you.\p"
	.string "NOTE\p"
	.string "All battles are double battles.\p"
	.string "It is recommended to strategize\n"
	.string "your teams accordingly to each\l"
	.string "trainer you face.\p"
	.string "TIP\p"
	.string "Beating trainers grives you battle\n"
	.string "points, which you can exchange for\l"
	.string "prizes at the end of the island.\p"
	.string "SECRET\p"
	.string "Beating this island not only\n"
	.string "earns bragging rights, but will\l"
	.string "also unlock a secret hidden story.$"

EventTicket_Text_RyukuIsland:
	.string "Show me your ticket.$"

EventTicket_Text_ShowRyukuIslandTicket:
	.string "Oh, my! That's a ticket to Ryuku\n"
	.string "Island! Exquisite!\p"
	.string "All Aboard!$"

EventTicket_Text_RyukuIslandSailBack:
	.string "Seen and captured everything?\p"
	.string "Want to sail back to LILYCOVE?$"
