TrainerIsland_TrainerCity_House3_MapScripts::
	.byte 0
	
TrainerIsland_TrainerCity_House3_EventScript_OldMan::
	msgbox TrainerIsland_TrainerCity_House3_Text_BeCareful, MSGBOX_NPC
	end	
	
TrainerIsland_TrainerCity_House3_EventScript_OldWoman::
	msgbox TrainerIsland_TrainerCity_House3_Text_Cult, MSGBOX_NPC
	end	
	
TrainerIsland_TrainerCity_House3_Text_BeCareful:
	.string "Be careful; I hear that there's\n"
	.string "a strange organization seeking\l"
	.string "world domination.\p"
	.string "And this time, the Team Aqua and\n"
	.string "Team Magma don't appear to be\l"
	.string "involved.$"
	
TrainerIsland_TrainerCity_House3_Text_Cult:
	.string "I've been watching the news;\n"
	.string "the cult organizations are using\l"
	.string "obscure, yet productive terms\l"
	.string "for their group names.\p"
	.string "Team Salvation…\p"
	.string "Team Satisfaction…\p"
	.string "To what ends do they seek?$"
