TrainerIsland_TrainerCity_House4_MapScripts::
	.byte 0
	
TrainerIsland_TrainerCity_House4_EventScript_Artist::
	msgbox TrainerIsland_TrainerCity_House4_Text_Artist, MSGBOX_NPC
	

TrainerIsland_TrainerCity_House4_Text_Artist:
	.string "I'm not a trainer, I'm an\n"
	.string "an artist.\p"
	.string "I can't battle, I can draw.\p"
	.string "I don't love pokemon,\n"
	.string "I love pictures.\p"
	.string "You won't beat me,\n"
	.string "but I will beat you.\p"
	.string "Because I'm an artist.\p"
	.string "That's what I am, and that's\n"
	.string "what I'll do.$"
